package in.industrend.platform.customer;
import java.util.UUID;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class CustomerService {
  public record Profile(UUID customerId,String mobile,String firstName,String lastName,String email,String addressLine1,String areaLandmark,String city,String state,String pinCode,boolean complete){}
  public record ProfileInput(String firstName,String lastName,String email,String addressLine1,String areaLandmark,String city,String state,String pinCode,UUID verificationChallengeId){}
  private final JdbcClient jdbc;public CustomerService(JdbcClient jdbc){this.jdbc=jdbc;}
  public Profile get(UUID id){return jdbc.sql("select c.customer_id,c.mobile_e164,c.first_name,c.last_name,c.email,a.address_line1,a.area_landmark,a.city,a.state_name,a.postal_code,c.profile_completed_at is not null from industrendindia.customers c left join industrendindia.customer_addresses a on a.customer_id=c.customer_id and a.is_default where c.customer_id=:id").param("id",id).query((r,n)->new Profile(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getBoolean(11))).single();}
  @Transactional public Profile save(UUID id,ProfileInput in){validate(in);var existing=get(id);var nextEmail=blankToNull(in.email());if(existing.complete()&&!java.util.Objects.equals(existing.email(),nextEmail))requireVerified(id,in.verificationChallengeId(),"EMAIL_CHANGE",existing.mobile());
    jdbc.sql("update industrendindia.customers set first_name=:f,last_name=:l,email=:e,profile_completed_at=coalesce(profile_completed_at,clock_timestamp()),updated_at=clock_timestamp() where customer_id=:id").param("f",in.firstName().trim()).param("l",in.lastName().trim()).param("e",nextEmail).param("id",id).update();
    jdbc.sql("insert into industrendindia.customer_addresses(address_id,customer_id,address_line1,area_landmark,city,state_name,postal_code,is_default) values(:aid,:id,:a,:land,:city,:state,:pin,true) on conflict (customer_id) where is_default do update set address_line1=excluded.address_line1,area_landmark=excluded.area_landmark,city=excluded.city,state_name=excluded.state_name,postal_code=excluded.postal_code,updated_at=clock_timestamp()").param("aid",UUID.randomUUID()).param("id",id).param("a",in.addressLine1().trim()).param("land",blankToNull(in.areaLandmark())).param("city",in.city().trim()).param("state",in.state().trim()).param("pin",in.pinCode()).update();return get(id);}
  @Transactional public Profile changeMobile(UUID id,String mobile,UUID challengeId){var normal=in.industrend.platform.auth.AuthService.normaliseMobile(mobile);requireVerified(id,challengeId,"MOBILE_CHANGE",normal);jdbc.sql("update industrendindia.customers set mobile_e164=:m,mobile_verified_at=clock_timestamp(),updated_at=clock_timestamp() where customer_id=:id").param("m",normal).param("id",id).update();return get(id);}
  private void requireVerified(UUID id,UUID challenge,String purpose,String destination){if(challenge==null)throw new IllegalArgumentException("OTP verification is required for this change");var count=jdbc.sql("select count(*) from industrendindia.otp_challenges where challenge_id=:ch and verified_customer_id=:id and purpose=:p and destination=:d and verified_at>clock_timestamp()-interval '10 minutes'").param("ch",challenge).param("id",id).param("p",purpose).param("d",destination).query(Integer.class).single();if(count!=1)throw new IllegalArgumentException("A recent matching OTP verification is required");}
  private void validate(ProfileInput i){if(blank(i.firstName())||blank(i.lastName())||blank(i.addressLine1())||blank(i.city())||blank(i.state()))throw new IllegalArgumentException("Name and delivery address are required");if(i.pinCode()==null||!i.pinCode().matches("[1-9][0-9]{5}"))throw new IllegalArgumentException("Enter a valid 6-digit PIN code");if(!blank(i.email())&&!i.email().matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"))throw new IllegalArgumentException("Enter a valid email address");}
  private boolean blank(String s){return s==null||s.isBlank();}private String blankToNull(String s){return blank(s)?null:s.trim().toLowerCase();}
}